---
# This playbook does a rolling update for all the Ceph services
#
# The value of 'serial:' adjusts the number of servers to be updated simultaneously.
# We recommend a value of 1, which means hosts of a group (e.g: monitor) will be
# upgraded one by one. It is really crucial for the update process to happen
# in a serialized fashion. DO NOT CHANGE THIS VALUE.
#
#
# If you run a Ceph community version, you have to change the variable: ceph_stable_release to the new release

- name: Confirm whether user really meant to upgrade the cluster
  hosts: localhost
  tags: always
  become: false
  gather_facts: false
  vars:
    mgr_group_name: mgrs

  vars_prompt:
    - name: ireallymeanit  # noqa: name[casing]
      prompt: Are you sure you want to upgrade the cluster?
      default: 'no'
      private: false

  tasks:
    - name: Exit playbook, if user did not mean to upgrade cluster
      ansible.builtin.fail:
        msg: >
          "Exiting rolling_update.yml playbook, cluster was NOT upgraded.
           To upgrade the cluster, either say 'yes' on the prompt or
           use `-e ireallymeanit=yes` on the command line when
           invoking the playbook"
      when: ireallymeanit != 'yes'

    - name: Import_role ceph-defaults
      ansible.builtin.import_role:
        name: ceph-defaults


- name: Gather facts and check the init system
  hosts:
    - "{{ mon_group_name|default('mons') }}"
    - "{{ osd_group_name|default('osds') }}"
    - "{{ mds_group_name|default('mdss') }}"
    - "{{ rgw_group_name|default('rgws') }}"
    - "{{ mgr_group_name|default('mgrs') }}"
    - "{{ rbdmirror_group_name|default('rbdmirrors') }}"
    - "{{ nfs_group_name|default('nfss') }}"
    - "{{ client_group_name|default('clients') }}"
    - "{{ monitoring_group_name|default('monitoring') }}"
  tags: always
  any_errors_fatal: true
  become: true
  gather_facts: false
  vars:
    delegate_facts_host: true
  tasks:
    - name: Gather facts on all Ceph hosts for following reference
      ansible.builtin.debug:
        msg: "gather facts on all Ceph hosts for following reference"

    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      when: not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])

    - name: Gather and delegate facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['all'] | difference(groups.get('clients', [])) }}"
      run_once: true
      when: delegate_facts_host | bool

    - name: Set_fact rolling_update
      ansible.builtin.set_fact:
        rolling_update: true

    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts

    - name: Import ceph-infra role
      ansible.builtin.import_role:
        name: ceph-infra
      tags: ceph_infra

    - name: Import ceph-validate role
      ansible.builtin.import_role:
        name: ceph-validate

    - name: Import ceph-container-engine role
      ansible.builtin.import_role:
        name: ceph-container-engine
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - (containerized_deployment | bool) or (dashboard_enabled | bool)

    - name: Import ceph-container-common role
      ansible.builtin.import_role:
        name: ceph-container-common
        tasks_from: registry
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - (containerized_deployment | bool) or (dashboard_enabled | bool)
        - ceph_docker_registry_auth | bool

    - name: Check ceph release in container image
      when:
        - groups.get(mon_group_name, []) | length > 0
        - containerized_deployment | bool
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      block:
        - name: Get the ceph release being deployed
          ansible.builtin.command: "{{ ceph_cmd }} --cluster {{ cluster }} --version"
          register: ceph_version
          changed_when: false

        - name: Check ceph release being deployed
          ansible.builtin.fail:
            msg: "This version of ceph-ansible is intended for upgrading to Ceph Squid only."
          when: "'squid' not in ceph_version.stdout.split()"


- name: Upgrade ceph rgws cluster
  vars:
    upgrade_ceph_packages: true
  hosts: "{{ rgw_group_name|default('rgws') }}"
  tags: rgws
  serial: 1
  become: true
  gather_facts: false
  tasks:

    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults
    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts

    - name: Stop ceph rgw when upgrading from stable-3.2  # noqa: ignore-errors
      ansible.builtin.systemd:
        name: ceph-radosgw@rgw.{{ rgw_zone }}.{{ ansible_facts['hostname'] }}
        state: stopped
        enabled: false
        masked: true
      ignore_errors: true

    - name: Stop ceph rgw
      ansible.builtin.systemd:
        name: ceph-radosgw@rgw.{{ rgw_zone }}.{{ ansible_facts['hostname'] }}.{{ item.instance_name }}
        state: stopped
        enabled: false
        masked: true
      with_items: "{{ rgw_instances }}"

    - name: Import ceph-handler role
      ansible.builtin.import_role:
        name: ceph-handler

    - name: Import ceph-common role
      ansible.builtin.import_role:
        name: ceph-common
      when: not containerized_deployment | bool

    - name: Import ceph-container-common role
      ansible.builtin.import_role:
        name: ceph-container-common
      when: containerized_deployment | bool

    - name: Import ceph-config role
      ansible.builtin.import_role:
        name: ceph-config

    - name: Import ceph-rgw role
      ansible.builtin.import_role:
        name: ceph-rgw
