---
# This playbook does a rolling update for all the Ceph services
#
# The value of 'serial:' adjusts the number of servers to be updated simultaneously.
# We recommend a value of 1, which means hosts of a group (e.g: monitor) will be
# upgraded one by one. It is really crucial for the update process to happen
# in a serialized fashion. DO NOT CHANGE THIS VALUE.
#
#
# If you run a Ceph community version, you have to change the variable: ceph_stable_release to the new release
#
# If you run Red Hat Ceph Storage and are doing a **major** update (e.g: from 2 to 3), you have to change the ceph_rhcs_version to a newer one
#

- name: confirm whether user really meant to upgrade the cluster
  hosts: localhost
  tags: always
  become: false
  gather_facts: false
  vars:
    - mgr_group_name: mgrs

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to upgrade the cluster?
      default: 'no'
      private: no

  tasks:
    - name: exit playbook, if user did not mean to upgrade cluster
      fail:
        msg: >
          "Exiting rolling_update.yml playbook, cluster was NOT upgraded.
           To upgrade the cluster, either say 'yes' on the prompt or
           use `-e ireallymeanit=yes` on the command line when
           invoking the playbook"
      when: ireallymeanit != 'yes'

    - name: import_role ceph-defaults
      import_role:
        name: ceph-defaults

    - name: check if a legacy grafana-server group exists
      import_role:
        name: ceph-facts
        tasks_from: convert_grafana_server_group_name.yml
      when: groups.get((grafana_server_group_name | default('grafana-server')), []) | length > 0


- name: gather facts and check the init system
  hosts:
    - "{{ mon_group_name|default('mons') }}"
    - "{{ osd_group_name|default('osds') }}"
    - "{{ mds_group_name|default('mdss') }}"
    - "{{ rgw_group_name|default('rgws') }}"
    - "{{ mgr_group_name|default('mgrs') }}"
    - "{{ rbdmirror_group_name|default('rbdmirrors') }}"
    - "{{ nfs_group_name|default('nfss') }}"
    - "{{ client_group_name|default('clients') }}"
    - "{{ iscsi_gw_group_name|default('iscsigws') }}"
    - "{{ monitoring_group_name|default('monitoring') }}"
  tags: always
  any_errors_fatal: True
  become: True
  gather_facts: False
  vars:
    delegate_facts_host: True
  tasks:
    - debug: msg="gather facts on all Ceph hosts for following reference"

    - import_role:
        name: ceph-defaults

    - name: gather facts
      setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      when: not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])

    - name: gather and delegate facts
      setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] | difference(groups.get('clients', [])) }}"
      run_once: true
      when: delegate_facts_host | bool

    - name: set_fact rolling_update
      set_fact:
        rolling_update: true

    - import_role:
        name: ceph-facts

    - import_role:
        name: ceph-infra
      tags: ceph_infra

    - import_role:
        name: ceph-validate

    - import_role:
        name: ceph-container-engine
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - (containerized_deployment | bool) or (dashboard_enabled | bool)

    - import_role:
        name: ceph-container-common
        tasks_from: registry
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - (containerized_deployment | bool) or (dashboard_enabled | bool)
        - ceph_docker_registry_auth | bool

    - name: check ceph release in container image
      when:
        - groups.get(mon_group_name, []) | length > 0
        - containerized_deployment | bool
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      block:
        - name: get the ceph release being deployed
          command: "{{ ceph_cmd }} --cluster {{ cluster }} --version"
          register: ceph_version
          changed_when: false

        - name: check ceph release being deployed
          fail:
            msg: "This version of ceph-ansible is intended for upgrading to Ceph Quincy only."
          when: "'quincy' not in ceph_version.stdout.split()"


- name: upgrade ceph rbd mirror node
  vars:
    upgrade_ceph_packages: True
  hosts: "{{ rbdmirror_group_name|default('rbdmirrors') }}"
  tags: rbdmirrors
  serial: 1
  become: True
  gather_facts: false
  tasks:
    - name: check for ceph rbd mirror services
      command: systemctl show --no-pager --property=Id --state=enabled ceph-rbd-mirror@*  # noqa 303
      changed_when: false
      register: rbdmirror_services

    - name: stop ceph rbd mirror
      service:
        name: "{{ item.split('=')[1] }}"
        state: stopped
        enabled: no
        masked: yes
      loop: "{{ rbdmirror_services.stdout_lines }}"

    - import_role:
        name: ceph-defaults
    - import_role:
        name: ceph-facts
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-common
      when: not containerized_deployment | bool
    - import_role:
        name: ceph-container-common
      when: containerized_deployment | bool
    - import_role:
        name: ceph-config
    - import_role:
        name: ceph-rbd-mirror


- name: upgrade ceph nfs node
  vars:
    upgrade_ceph_packages: True
  hosts: "{{ nfs_group_name|default('nfss') }}"
  tags: nfss
  serial: 1
  become: True
  gather_facts: false
  tasks:
    # failed_when: false is here so that if we upgrade
    # from a version of ceph that does not have nfs-ganesha
    # then this task will not fail
    - name: stop ceph nfs
      systemd:
        name: nfs-ganesha
        state: stopped
        enabled: no
        masked: yes
      failed_when: false
      when: not containerized_deployment | bool

    - name: systemd stop nfs container
      systemd:
        name: ceph-nfs@{{ ceph_nfs_service_suffix | default(ansible_facts['hostname']) }}
        state: stopped
        enabled: no
        masked: yes
      failed_when: false
      when:
        - ceph_nfs_enable_service | bool
        - containerized_deployment | bool

    - import_role:
        name: ceph-defaults
    - import_role:
        name: ceph-facts
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-common
      when: not containerized_deployment | bool
    - import_role:
        name: ceph-container-common
      when: containerized_deployment | bool
    - import_role:
        name: ceph-config
    - import_role:
        name: ceph-nfs


- name: upgrade ceph iscsi gateway node
  vars:
    upgrade_ceph_packages: True
  hosts: "{{ iscsi_gw_group_name|default('iscsigws') }}"
  tags: iscsigws
  serial: 1
  become: True
  gather_facts: false
  tasks:
    # failed_when: false is here so that if we upgrade
    # from a version of ceph that does not have iscsi gws
    # then this task will not fail
    - name: stop ceph iscsi services
      systemd:
        name: '{{ item }}'
        state: stopped
        enabled: no
        masked: yes
      failed_when: false
      with_items:
        - rbd-target-api
        - rbd-target-gw
        - tcmu-runner

    - import_role:
        name: ceph-defaults
    - import_role:
        name: ceph-facts
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-common
      when: not containerized_deployment | bool
    - import_role:
        name: ceph-container-common
      when: containerized_deployment | bool
    - import_role:
        name: ceph-config
    - import_role:
        name: ceph-iscsi-gw


- name: upgrade ceph client node
  vars:
    upgrade_ceph_packages: True
  hosts: "{{ client_group_name|default('clients') }}"
  tags: clients
  serial: "{{ client_update_batch | default(20) }}"
  become: True
  gather_facts: false
  tasks:
    - import_role:
        name: ceph-defaults
    - import_role:
        name: ceph-facts
        tasks_from: container_binary.yml
      when: containerized_deployment | bool
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-common
      when: not containerized_deployment | bool
    - import_role:
        name: ceph-container-common
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - containerized_deployment | bool


- name: upgrade ceph-crash daemons
  hosts:
    - "{{ mon_group_name | default('mons') }}"
    - "{{ osd_group_name | default('osds') }}"
    - "{{ mds_group_name | default('mdss') }}"
    - "{{ rgw_group_name | default('rgws') }}"
    - "{{ rbdmirror_group_name | default('rbdmirrors') }}"
    - "{{ mgr_group_name | default('mgrs') }}"
  tags:
    - post_upgrade
    - crash
  gather_facts: false
  become: true
  tasks:
    - name: stop the ceph-crash service
      systemd:
        name: "{{ 'ceph-crash@' + ansible_facts['hostname'] if containerized_deployment | bool else 'ceph-crash.service' }}"
        state: stopped

    # it needs to be done in a separate task otherwise the stop just before doesn't work.
    - name: mask and disable the ceph-crash service
      systemd:
        name: "{{ 'ceph-crash@' + ansible_facts['hostname'] if containerized_deployment | bool else 'ceph-crash.service' }}"
        enabled: no
        masked: yes

    - import_role:
        name: ceph-defaults
    - import_role:
        name: ceph-facts
        tasks_from: container_binary.yml
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-crash

- name: complete upgrade
  hosts: "{{ mon_group_name | default('mons') }}"
  tags: post_upgrade
  become: True
  gather_facts: false
  tasks:
    - import_role:
        name: ceph-defaults
    - import_role:
        name: ceph-facts
        tasks_from: container_binary.yml

    - name: container | disallow pre-quincy OSDs and enable all new quincy-only functionality
      command: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_facts']['hostname'] }} ceph --cluster {{ cluster }} osd require-osd-release quincy"
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: True
      when:
        - containerized_deployment | bool
        - groups.get(mon_group_name, []) | length > 0

    - name: non container | disallow pre-quincy OSDs and enable all new quincy-only functionality
      command: "ceph --cluster {{ cluster }} osd require-osd-release quincy"
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: True
      when:
        - not containerized_deployment | bool
        - groups.get(mon_group_name, []) | length > 0

- name: upgrade node-exporter
  hosts:
    - "{{ mon_group_name|default('mons') }}"
    - "{{ osd_group_name|default('osds') }}"
    - "{{ mds_group_name|default('mdss') }}"
    - "{{ rgw_group_name|default('rgws') }}"
    - "{{ mgr_group_name|default('mgrs') }}"
    - "{{ rbdmirror_group_name|default('rbdmirrors') }}"
    - "{{ nfs_group_name|default('nfss') }}"
    - "{{ iscsi_gw_group_name|default('iscsigws') }}"
    - "{{ monitoring_group_name|default('monitoring') }}"
  tags: monitoring
  gather_facts: false
  become: true
  tasks:
    - import_role:
        name: ceph-defaults

    - name: with dashboard configuration
      when: dashboard_enabled | bool
      block:
        - name: stop node-exporter
          service:
            name: node_exporter
            state: stopped
          failed_when: false

        - import_role:
            name: ceph-facts
        - import_role:
            name: ceph-container-engine
        - import_role:
            name: ceph-container-common
            tasks_from: registry
          when:
            - not containerized_deployment | bool
            - ceph_docker_registry_auth | bool
        - import_role:
            name: ceph-node-exporter

- name: upgrade monitoring node
  hosts: "{{ monitoring_group_name }}"
  tags: monitoring
  gather_facts: false
  become: true
  tasks:
    - import_role:
        name: ceph-defaults

    - name: with dashboard configuration
      when: dashboard_enabled | bool
      block:
        - name: stop monitoring services
          service:
            name: '{{ item }}'
            state: stopped
          failed_when: false
          with_items:
            - alertmanager
            - prometheus
            - grafana-server

        - import_role:
            name: ceph-facts
        - import_role:
            name: ceph-facts
            tasks_from: grafana
        - import_role:
            name: ceph-prometheus
        - import_role:
            name: ceph-grafana

- name: upgrade ceph dashboard
  hosts: "{{ groups[mgr_group_name] | default(groups[mon_group_name]) | default(omit) }}"
  tags: monitoring
  gather_facts: false
  become: true
  tasks:
    - import_role:
        name: ceph-defaults

    - name: with dashboard configuration
      when: dashboard_enabled | bool
      block:
        - import_role:
            name: ceph-facts
        - import_role:
            name: ceph-facts
            tasks_from: grafana
        - import_role:
            name: ceph-dashboard

- name: switch any existing crush buckets to straw2
  hosts: "{{ mon_group_name | default('mons') }}[0]"
  tags: post_upgrade
  become: true
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - import_role:
        name: ceph-defaults

    - import_role:
        name: ceph-facts
        tasks_from: container_binary.yml

    - name: set_fact ceph_cmd
      set_fact:
        ceph_cmd: "{{ container_binary + ' run --rm --net=host -v /etc/ceph:/etc/ceph:z --entrypoint=ceph ' + ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment | bool else 'ceph' }}"

    - name: backup the crushmap
      command: "{{ ceph_cmd }} --cluster {{ cluster }} osd getcrushmap -o /etc/ceph/{{ cluster }}-crushmap"
      changed_when: false

    - block:
        - name: switch crush buckets to straw2
          command: "{{ ceph_cmd }} --cluster {{ cluster }} osd crush set-all-straw-buckets-to-straw2"
          changed_when: false
      rescue:
        - name: restore the crushmap
          command: "{{ ceph_cmd }} --cluster {{ cluster }} osd setcrushmap -i /etc/ceph/{{ cluster }}-crushmap"
          changed_when: false

        - name: inform that the switch to straw2 buckets failed
          fail:
            msg: >
              "An attempt to switch to straw2 bucket was made but failed.
               Check the cluster status."

    - name: remove crushmap backup
      file:
        path: /etc/ceph/{{ cluster }}-crushmap
        state: absent

- name: show ceph status
  hosts: "{{ mon_group_name|default('mons') }}"
  tags: always
  become: True
  gather_facts: false
  tasks:
    - import_role:
        name: ceph-defaults

    - name: set_fact container_exec_cmd_status
      set_fact:
        container_exec_cmd_status: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_facts']['hostname'] }}"
      when: containerized_deployment | bool

    - name: show ceph status
      command: "{{ container_exec_cmd_status|default('') }} ceph --cluster {{ cluster }} -s"
      changed_when: false
      run_once: True
      delegate_to: "{{ groups[mon_group_name][0] }}"

    - name: show all daemons version
      command: "{{ container_exec_cmd_status|default('') }} ceph --cluster {{ cluster }} versions"
      run_once: True
      delegate_to: "{{ groups[mon_group_name][0] }}"
      changed_when: false
