---
# This playbook does a rolling update for all the Ceph services
#
# The value of 'serial:' adjusts the number of servers to be updated simultaneously.
# We recommend a value of 1, which means hosts of a group (e.g: monitor) will be
# upgraded one by one. It is really crucial for the update process to happen
# in a serialized fashion. DO NOT CHANGE THIS VALUE.
#
#
# If you run a Ceph community version, you have to change the variable: ceph_stable_release to the new release

- name: Confirm whether user really meant to upgrade the cluster
  hosts: localhost
  tags: always
  become: false
  gather_facts: false
  vars:
    mgr_group_name: mgrs

  vars_prompt:
    - name: ireallymeanit  # noqa: name[casing]
      prompt: Are you sure you want to upgrade the cluster?
      default: 'no'
      private: false

  tasks:
    - name: Exit playbook, if user did not mean to upgrade cluster
      ansible.builtin.fail:
        msg: >
          "Exiting rolling_update.yml playbook, cluster was NOT upgraded.
           To upgrade the cluster, either say 'yes' on the prompt or
           use `-e ireallymeanit=yes` on the command line when
           invoking the playbook"
      when: ireallymeanit != 'yes'

    - name: Import_role ceph-defaults
      ansible.builtin.import_role:
        name: ceph-defaults


- name: Gather facts and check the init system
  hosts:
    - "{{ mon_group_name|default('mons') }}"
    - "{{ osd_group_name|default('osds') }}"
    - "{{ mds_group_name|default('mdss') }}"
    - "{{ rgw_group_name|default('rgws') }}"
    - "{{ mgr_group_name|default('mgrs') }}"
    - "{{ rbdmirror_group_name|default('rbdmirrors') }}"
    - "{{ nfs_group_name|default('nfss') }}"
    - "{{ client_group_name|default('clients') }}"
    - "{{ monitoring_group_name|default('monitoring') }}"
  tags: always
  any_errors_fatal: true
  become: true
  gather_facts: false
  vars:
    delegate_facts_host: true
  tasks:
    - name: Gather facts on all Ceph hosts for following reference
      ansible.builtin.debug:
        msg: "gather facts on all Ceph hosts for following reference"

    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      when: not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])

    - name: Gather and delegate facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
          - '!facter'
          - '!ohai'
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['all'] | difference(groups.get('clients', [])) }}"
      run_once: true
      when: delegate_facts_host | bool

    - name: Set_fact rolling_update
      ansible.builtin.set_fact:
        rolling_update: true

    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts

    - name: Import ceph-infra role
      ansible.builtin.import_role:
        name: ceph-infra
      tags: ceph_infra

    - name: Import ceph-validate role
      ansible.builtin.import_role:
        name: ceph-validate

    - name: Import ceph-container-engine role
      ansible.builtin.import_role:
        name: ceph-container-engine
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - (containerized_deployment | bool) or (dashboard_enabled | bool)

    - name: Import ceph-container-common role
      ansible.builtin.import_role:
        name: ceph-container-common
        tasks_from: registry
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - (containerized_deployment | bool) or (dashboard_enabled | bool)
        - ceph_docker_registry_auth | bool

    - name: Check ceph release in container image
      when:
        - groups.get(mon_group_name, []) | length > 0
        - containerized_deployment | bool
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      block:
        - name: Get the ceph release being deployed
          ansible.builtin.command: "{{ ceph_cmd }} --cluster {{ cluster }} --version"
          register: ceph_version
          changed_when: false

        - name: Check ceph release being deployed
          ansible.builtin.fail:
            msg: "This version of ceph-ansible is intended for upgrading to Ceph Squid only."
          when: "'squid' not in ceph_version.stdout.split()"


- name: Upgrade ceph rbd mirror node
  vars:
    upgrade_ceph_packages: true
  hosts: "{{ rbdmirror_group_name|default('rbdmirrors') }}"
  tags: rbdmirrors
  serial: 1
  become: true
  gather_facts: false
  tasks:
    - name: Check for ceph rbd mirror services
      ansible.builtin.command: systemctl show --no-pager --property=Id --state=enabled ceph-rbd-mirror@*  # noqa command-instead-of-module
      changed_when: false
      register: rbdmirror_services

    - name: Stop ceph rbd mirror
      ansible.builtin.service:
        name: "{{ item.split('=')[1] }}"
        state: stopped
        enabled: false
        masked: true
      loop: "{{ rbdmirror_services.stdout_lines }}"

    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts

    - name: Import ceph-handler role
      ansible.builtin.import_role:
        name: ceph-handler

    - name: Import ceph-common role
      ansible.builtin.import_role:
        name: ceph-common
      when: not containerized_deployment | bool

    - name: Import ceph-container-common role
      ansible.builtin.import_role:
        name: ceph-container-common
      when: containerized_deployment | bool

    - name: Import ceph-config role
      ansible.builtin.import_role:
        name: ceph-config

    - name: Import ceph-rbd-mirror role
      ansible.builtin.import_role:
        name: ceph-rbd-mirror


- name: Upgrade ceph nfs node
  vars:
    upgrade_ceph_packages: true
  hosts: "{{ nfs_group_name|default('nfss') }}"
  tags: nfss
  serial: 1
  become: true
  gather_facts: false
  tasks:
    # failed_when: false is here so that if we upgrade
    # from a version of ceph that does not have nfs-ganesha
    # then this task will not fail
    - name: Stop ceph nfs
      ansible.builtin.systemd:
        name: nfs-ganesha
        state: stopped
        enabled: false
        masked: true
      failed_when: false
      when: not containerized_deployment | bool

    - name: Systemd stop nfs container
      ansible.builtin.systemd:
        name: ceph-nfs@{{ ceph_nfs_service_suffix | default(ansible_facts['hostname']) }}
        state: stopped
        enabled: false
        masked: true
      failed_when: false
      when:
        - ceph_nfs_enable_service | bool
        - containerized_deployment | bool

    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts

    - name: Import ceph-handler role
      ansible.builtin.import_role:
        name: ceph-handler

    - name: Import ceph-common role
      ansible.builtin.import_role:
        name: ceph-common
      when: not containerized_deployment | bool

    - name: Import ceph-container-common role
      ansible.builtin.import_role:
        name: ceph-container-common
      when: containerized_deployment | bool

    - name: Import ceph-config role
      ansible.builtin.import_role:
        name: ceph-config

    - name: Import ceph-nfs role
      ansible.builtin.import_role:
        name: ceph-nfs

- name: Upgrade ceph client node
  vars:
    upgrade_ceph_packages: true
  hosts: "{{ client_group_name|default('clients') }}"
  tags: clients
  serial: "{{ client_update_batch | default(20) }}"
  become: true
  gather_facts: false
  tasks:
    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults
    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts
        tasks_from: container_binary.yml
      when: containerized_deployment | bool
    - name: Import ceph-handler role
      ansible.builtin.import_role:
        name: ceph-handler
    - name: Import ceph-common role
      ansible.builtin.import_role:
        name: ceph-common
      when: not containerized_deployment | bool
    - name: Import ceph-container-common role
      ansible.builtin.import_role:
        name: ceph-container-common
      when:
        - (group_names != ['clients']) or (inventory_hostname == groups.get('clients', [''])|first)
        - containerized_deployment | bool


- name: Upgrade ceph-crash daemons
  hosts:
    - "{{ mon_group_name | default('mons') }}"
    - "{{ osd_group_name | default('osds') }}"
    - "{{ mds_group_name | default('mdss') }}"
    - "{{ rgw_group_name | default('rgws') }}"
    - "{{ rbdmirror_group_name | default('rbdmirrors') }}"
    - "{{ mgr_group_name | default('mgrs') }}"
  tags:
    - post_upgrade
    - crash
  gather_facts: false
  become: true
  tasks:
    - name: Stop the ceph-crash service
      ansible.builtin.systemd:
        name: "{{ 'ceph-crash@' + ansible_facts['hostname'] if containerized_deployment | bool else 'ceph-crash.service' }}"
        state: stopped

    # it needs to be done in a separate task otherwise the stop just before doesn't work.
    - name: Mask and disable the ceph-crash service
      ansible.builtin.systemd:
        name: "{{ 'ceph-crash@' + ansible_facts['hostname'] if containerized_deployment | bool else 'ceph-crash.service' }}"
        enabled: false
        masked: true

    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults
    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts
        tasks_from: container_binary.yml
    - name: Import ceph-handler role
      ansible.builtin.import_role:
        name: ceph-handler
    - name: Import ceph-crash role
      ansible.builtin.import_role:
        name: ceph-crash

- name: Upgrade ceph-exporter daemons
  hosts:
    - "{{ mon_group_name | default('mons') }}"
    - "{{ osd_group_name | default('osds') }}"
    - "{{ mds_group_name | default('mdss') }}"
    - "{{ rgw_group_name | default('rgws') }}"
    - "{{ rbdmirror_group_name | default('rbdmirrors') }}"
    - "{{ mgr_group_name | default('mgrs') }}"
  tags:
    - post_upgrade
    - ceph-exporter
  gather_facts: false
  become: true
  tasks:
    - name: Exit ceph-exporter upgrade if non containerized deployment
      ansible.builtin.meta: end_play
      when: not containerized_deployment | bool

    - name: Stop the ceph-exporter service
      ansible.builtin.systemd:
        name: "{{ 'ceph-exporter@' + ansible_facts['hostname'] if containerized_deployment | bool else 'ceph-exporter.service' }}"
        state: stopped

    # it needs to be done in a separate task otherwise the stop just before doesn't work.
    - name: Mask and disable the ceph-exporter service
      ansible.builtin.systemd:
        name: "{{ 'ceph-exporter@' + ansible_facts['hostname'] if containerized_deployment | bool else 'ceph-exporter.service' }}"
        enabled: false
        masked: true

    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults
    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts
        tasks_from: container_binary.yml
    - name: Import ceph-handler role
      ansible.builtin.import_role:
        name: ceph-handler
    - name: Import ceph-exporter role
      ansible.builtin.import_role:
        name: ceph-exporter

- name: Complete upgrade
  hosts: "{{ mon_group_name | default('mons') }}"
  tags: post_upgrade
  become: true
  gather_facts: false
  tasks:
    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts
        tasks_from: container_binary.yml

    - name: Container | disallow pre-squid OSDs and enable all new squid-only functionality
      ansible.builtin.command: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_facts']['hostname'] }} ceph --cluster {{ cluster }} osd require-osd-release squid"
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      changed_when: false
      when:
        - containerized_deployment | bool
        - groups.get(mon_group_name, []) | length > 0

    - name: Non container | disallow pre-squid OSDs and enable all new squid-only functionality
      ansible.builtin.command: "ceph --cluster {{ cluster }} osd require-osd-release squid"
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
      changed_when: false
      when:
        - not containerized_deployment | bool
        - groups.get(mon_group_name, []) | length > 0

- name: Upgrade node-exporter
  hosts:
    - "{{ mon_group_name|default('mons') }}"
    - "{{ osd_group_name|default('osds') }}"
    - "{{ mds_group_name|default('mdss') }}"
    - "{{ rgw_group_name|default('rgws') }}"
    - "{{ mgr_group_name|default('mgrs') }}"
    - "{{ rbdmirror_group_name|default('rbdmirrors') }}"
    - "{{ nfs_group_name|default('nfss') }}"
    - "{{ monitoring_group_name|default('monitoring') }}"
  tags: monitoring
  gather_facts: false
  become: true
  tasks:
    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: With dashboard configuration
      when: dashboard_enabled | bool
      block:
        - name: Stop node-exporter
          ansible.builtin.service:
            name: node_exporter
            state: stopped
          failed_when: false

        - name: Import ceph-facts role
          ansible.builtin.import_role:
            name: ceph-facts
        - name: Import ceph-container-engine role
          ansible.builtin.import_role:
            name: ceph-container-engine
        - name: Import ceph-container-common role
          ansible.builtin.import_role:
            name: ceph-container-common
            tasks_from: registry
          when:
            - not containerized_deployment | bool
            - ceph_docker_registry_auth | bool
        - name: Import ceph-node-exporter role
          ansible.builtin.import_role:
            name: ceph-node-exporter

- name: Upgrade monitoring node
  hosts: "{{ monitoring_group_name|default('monitoring') }}"
  tags: monitoring
  gather_facts: false
  become: true
  tasks:
    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: With dashboard configuration
      when: dashboard_enabled | bool
      block:
        - name: Stop monitoring services
          ansible.builtin.service:
            name: '{{ item }}'
            state: stopped
          failed_when: false
          with_items:
            - alertmanager
            - prometheus
            - grafana-server

        # - name: Import ceph-facts role
        #   ansible.builtin.import_role:
        #     name: ceph-facts
        - name: Import ceph-facts role
          ansible.builtin.import_role:
            name: ceph-facts
            tasks_from: grafana
        - name: Import ceph-prometheus role
          ansible.builtin.import_role:
            name: ceph-prometheus
        - name: Import ceph-grafana role
          ansible.builtin.import_role:
            name: ceph-grafana

- name: Upgrade ceph dashboard
  hosts: "{{ groups[mgr_group_name|default('mgrs')] | default(groups[mon_group_name|default('mons')]) | default(omit) }}"
  tags: monitoring
  gather_facts: false
  become: true
  tasks:
    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: With dashboard configuration
      when: dashboard_enabled | bool
      block:
        - name: Import ceph-facts role
          ansible.builtin.import_role:
            name: ceph-facts

        - name: Import ceph-facts role
          ansible.builtin.import_role:
            name: ceph-facts
            tasks_from: grafana

        - name: Import ceph-dashboard role
          ansible.builtin.import_role:
            name: ceph-dashboard

- name: Switch any existing crush buckets to straw2
  hosts: "{{ mon_group_name | default('mons') }}[0]"
  tags: post_upgrade
  become: true
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: Import ceph-facts role
      ansible.builtin.import_role:
        name: ceph-facts
        tasks_from: container_binary.yml

    - name: Set_fact ceph_cmd
      ansible.builtin.set_fact:
        ceph_cmd: "{{ container_binary + ' run --rm --net=host -v /etc/ceph:/etc/ceph:z --entrypoint=ceph ' + ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment | bool else 'ceph' }}"

    - name: Backup the crushmap
      ansible.builtin.command: "{{ ceph_cmd }} --cluster {{ cluster }} osd getcrushmap -o /etc/ceph/{{ cluster }}-crushmap"
      changed_when: false

    - name: Migrate crush buckets to straw2
      block:
        - name: Switch crush buckets to straw2
          ansible.builtin.command: "{{ ceph_cmd }} --cluster {{ cluster }} osd crush set-all-straw-buckets-to-straw2"
          changed_when: false
      rescue:
        - name: Restore the crushmap
          ansible.builtin.command: "{{ ceph_cmd }} --cluster {{ cluster }} osd setcrushmap -i /etc/ceph/{{ cluster }}-crushmap"
          changed_when: false

        - name: Inform that the switch to straw2 buckets failed
          ansible.builtin.fail:
            msg: >
              "An attempt to switch to straw2 bucket was made but failed.
               Check the cluster status."

    - name: Remove crushmap backup
      ansible.builtin.file:
        path: /etc/ceph/{{ cluster }}-crushmap
        state: absent

- name: Show ceph status
  hosts: "{{ mon_group_name|default('mons') }}"
  tags: always
  become: true
  gather_facts: false
  tasks:
    - name: Import ceph-defaults role
      ansible.builtin.import_role:
        name: ceph-defaults

    - name: Set_fact container_exec_cmd_status
      ansible.builtin.set_fact:
        container_exec_cmd_status: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_facts']['hostname'] }}"
      when: containerized_deployment | bool

    - name: Show ceph status
      ansible.builtin.command: "{{ container_exec_cmd_status | default('') }} ceph --cluster {{ cluster }} -s"
      changed_when: false
      run_once: true
      delegate_to: "{{ groups[mon_group_name][0] }}"

    - name: Show all daemons version
      ansible.builtin.command: "{{ container_exec_cmd_status | default('') }} ceph --cluster {{ cluster }} versions"
      run_once: true
      delegate_to: "{{ groups[mon_group_name][0] }}"
      changed_when: false
