
- name: Disable Puppet
  hosts: mons, osds, mdss
  gather_facts: no
  ignore_errors: yes
  ignore_unreachable: yes
  tasks:
  - name: disable puppet
    command: puppet agent --disable "jmamma - puppet disable"
 

