name: signed-off
on: [pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: "${GITHUB_WORKSPACE}/tests/scripts/workflows/signed-off.sh"